### PR TITLE
Adapts skeleton meta-text description.

### PR DESCRIPTION
**Pull request by vulder**
Changes skeleton meta-text description wording from instructions to description. This should make it clearer for people that the italics descriptions should be kept in every topic.

### CODE REVIEW

**Comment by vulder** [comment]
@cjdb @rwdougla What do you think. Is it enough to change the wording from `instructions` to `descriptions`, to make it clear that one should keep the italics text in the doc?

As an alternative, I can add explicit wording that mentions this, like:
```
..., so please don't remove these descriptions when editing the topic.
```

**Comment by vulder** [comment]
@rwdougla What are you thoughts about the wording?

**Comment by rwdougla** [comment]
Impressively, I think the one word change _does_ mitigate my concern. Your extended "alternative" is likely to save you from repeating this, though, and so probably has some value, too.

**Comment by vulder** [comment]
> Impressively, I think the one word change _does_ mitigate my concern. Your extended "alternative" is likely to save you from repeating this, though, and so probably has some value, too.

:+1: It choose the long version and updated all topics. Could you review/approve this PR?

**Review by jcvw — APPROVED** [review]
Looks good tom me.

**Pull request merged**
