### PR TITLE
Adds topic updater script

### PR DESCRIPTION
**Pull request by vulder**
The topic_updater can be used to add meta text to new topics or to update the skeleton text for all documents. This tool helps us to keep the skeleton meta text in sync.

### CODE REVIEW

**Comment by vulder** [comment]
@cjdb could you please take a look at the first draft of the topic updater script. I'll still need to update the check mechanic to work in all cases but update already works. :)

**Comment by cjdb** [comment]
Are there any tests that you can submit alongside this?

**Comment by vulder** [comment]
Sure, I'll be happy to, currently I try to maintain them a long side the repository because I wasn't sure where to put them. At the moment all top level folder symbolize teaching modules, so putting something like `tests` or `tools` there could be confusing. I thought about a few options but could not decide. Which of these do you like best, or do you have other ideas?

* This one is more verbose but fully separated.
```
sg20_1
├── functions
├── internal
│   ├── tests
│   │   ├── foo_test.py
│   │   └── TEST_INPUTS
│   └── tools
│       └── topic_updater.py
└── object-model
```

* Here `tools` could be confused with the module `Tooling`
```
sg20_2
├── functions
├── object-model
└── tools
    ├── tests
    │   ├── foo_test.py
    │   └── TEST_INPUTS
    └── topic_updater.py
```

* Here `tests` could be confused with a possible future module related to testing and also has the problem that all tool scripts are top-level. Besides that, it has the benefit that tooling script are easier discoverable. 
```
sg20_3
├── functions
├── object-model
├── tests
│   ├── foo_test.py
│   └── TEST_INPUTS
└── topic_updater.py
```

**Comment by cjdb** [comment]
This is related to tooling, so I'd suggest `tools/tests`.

**Review by cjdb — APPROVED** [review]

**Pull request merged**
